### ISSUE TITLE
Fail to train model 

### ISSUE THREAD

**Issue by RalphChahine** [cloud-annotations/training#191]
I have been using cloud-annotations to train my visual recognitions models successfully. 
However, since yesterday I keep getting the following errors when trying to train my models : 
```
error Training failed.
error Command failed with exit code 1.
```
Here are some logs of the training:
```
CACLI-TRAINING-FAILED
Training exited with error code 1
Failed: learner_exit_code: 1
```
Here is an odd error appearing also from the logs:
```
TypeError: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.
```

Thanks for the product by the way I love it

**Comment by bourdakos1** [comment]
oh thats strange, what model type are you training?

**Comment by RalphChahine** [comment]
I am doing object detection with IBM cloud annotations with localization annotation type, using Watson machine learning services.  The training consistency fails around step 390.

**Comment by bourdakos1** [comment]
Could be related to this issue: https://github.com/rbgirshick/py-faster-rcnn/issues/481

Watson machine learning could have changed numpy versions, I’ll look into it :)

**Comment by bourdakos1** [comment]
numpy version 1.18 was causing issues

cacli version 1.2.29 should fix the problem :)

please reopen this if you're still having trouble

**Comment by RalphChahine** [comment]
@bourdakos1 Thank you for your great work. 

Unfortunately, the same problem still occurs when I train model from the CLI. Maybe due to the fact that the latest version for cloud-annotations package available in [yarn](https://yarnpkg.com/package/cloud-annotations) is 1.2.1. Is there any way you could update it? 

I am able to train my model online now at least, but I can't find a way of changing the number of steps for my training if i perform it online, therefore I would need to have an updated version of the CLI.

**Comment by bourdakos1** [comment]
@RalphChahine I've deprecated the node version of the CLI in favor of golang. You can install the new version of the CLI with homebrew if you have a mac (`brew install cloud-annotations/tap/cacli`)

If you want to continue using the node version you can download the latest `training.zip` file from the [releases](https://github.com/cloud-annotations/training/releases) and call:
```
cacli train custom-training.zip
```
